#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import argparse
import sys
from commands import build, develop, clean, test, run
from util import str2yamlfile

DEV_COMMANDS = {"develop": develop, "build": build, "test": test, "clean": clean}


def parse_args(cli_args):
    parser = argparse.ArgumentParser(description="mtriage dev scripts")
    subparsers = parser.add_subparsers(dest="__base")

    run_p = subparsers.add_parser("run")
    run_p.add_argument("yaml", type=str2yamlfile)
    run_p.add_argument("--tag", default="dev")
    run_p.add_argument("--gpu", action="store_true")
    run_p.add_argument("--dry", action="store_true")

    dev_p = subparsers.add_parser("dev")
    dev_p.add_argument("--whitelist")
    dev_p.add_argument("--blacklist")
    dev_p.add_argument("--tag", default="dev")
    dev_p.add_argument("--gpu", action="store_true")
    dev_p.add_argument("--dry", action="store_true")
    dev_p.add_argument(
        "command",
        choices=DEV_COMMANDS.keys(),
        default="develop",
        const="develop",
        nargs="?",
    )

    return parser.parse_args(cli_args)


if __name__ == "__main__":
    args = parse_args(sys.argv[1:])

    if args.__base == "dev":
        DEV_COMMANDS[args.command](args)
    else:
        run(args)
