export default {
  FETCH_ELEMENT_INDEX_ATTEMPT: 'FETCH_ELEMENT_INDEX_ATTEMPT',
  FETCH_ELEMENT_INDEX: 'FETCH_ELEMENT_INDEX',
  FETCH_ELEMENT_INDEX_ERROR: 'FETCH_ELEMENT_INDEX_ERROR',
  FETCH_ELEMENT_ATTEMPT: 'FETCH_ELEMENT_ATTEMPT',
  FETCH_ELEMENT: 'FETCH_ELEMENT',
  FETCH_ELEMENT_ERROR: 'FETCH_ELEMENT_ERROR',
  FETCH_ELEMENTS_ATTEMPT: 'FETCH_ELEMENTS_ATTEMPT',
  FETCH_ELEMENTS: 'FETCH_ELEMENTS',
  FETCH_ELEMENTS_ERROR: 'FETCH_ELEMENTS_ERROR'
}
